# Generated by Django 3.2.7 on 2021-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_activitys_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='activities',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
